bug:
  - bug
  - error
  - fallo
  - problema
  - crash
  - broken
  - no funciona
  - doesnt work
  - fails
  - failure
  - unexpected behavior
  - malfunction
  - caseSensitive: false

documentation:
  - documentation
  - documentación
  - docs
  - readme
  - documentar
  - manual
  - guía
  - doc
  - wiki
  - typo
  - spelling mistake
  - caseSensitive: false

enhancement:
  - enh
  - impr
  - enhancement
  - mejora
  - optimizar
  - me gustaría que
  - más rápido
  - refactor
  - rendimiento
  - enhancement
  - improve
  - improvement
  - performance
  - refactor
  - make better
  - caseSensitive: false

feature:
  - feat
  - nueva función
  - agregar
  - añadir
  - feature request
  - funcionalidad
  - add
  - new feature
  - implement
  - support for
  - extend
  - include
  - create
  - crear
  - caseSensitive: false

invalid:
  - inv
  - invalido
  - invalida
  - no válido
  - no válida
  - incorrecto
  - incorrecta
  - error de sintaxis
  - error de formato
  - no aplica
  - no entiendo
  - irrelevante
  - no tiene sentido
  - no es relevante
  - invalid
  - not valid
  - not applicable
  - unclear
  - nonsensical
  - caseSensitive: false

question:
  - qst
  - pregunta
  - consulta
  - preguntar
  - consultar
  - dudar
  - necesito ayuda
  - ayuda requerida
  - cómo
  - por qué
  - porque
  - para qué
  - qué hace
  - duda
  - question
  - how do i
  - why does
  - what is
  - can someone explain
  - i don’t understand
  - caseSensitive: false

help wanted:
  - help
  - ayuda
  - no sé cómo
  - alguien puede
  - colaborar
  - necesito ayuda
  - help wanted
  - need help
  - anyone can help
  - looking for help
  - collaborate
  - caseSensitive: false

wontfix:
  - no se arreglará
  - no planeamos arreglarlo
  - no es prioridad
  - no tiene solución
  - wontfix
  - wont fix
  - wont be addressed
  - intentional
  - caseSensitive: false

duplicate:
  - dup
  - duplicado
  - ya existe
  - repetido
  - duplicate
  - already reported
  - same issue
  - redundant
  - caseSensitive: false

good first issue:
  - good first
  - gfi
  - tarea sencilla
  - principiante
  - fácil de resolver
  - ideal para empezar
  - primer issue
  - first issue
  - good first issue
  - easy fix
  - beginner friendly
  - simple task
  - caseSensitive: false
