name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x  

      - name: Build project
        run: deno run --allow-read --allow-write build.ts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
