name: Add new issues to project panel

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/binarybrains-upiicsa/projects/2
          github-token: ${{ secrets.MY_PAT }}
