name: "Issue Labeler"
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: MaximilianAnzinger/issue-labeler@1.0.0 # Use the latest version
        with:
          configuration-path: .github/issue-labeler.yml
          repo-token: ${{ github.token }}
          include-title: 1 // Default is 1
          include-body: 0 // Default is 1
