name: Lint Hacktion

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Obtener el c贸digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Deno en el runner
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          
      - name: Install packages
        run: deno install
      # Paso 4: Ejecutar ESLint para verificar el c贸digo
      - name: Run lint
        run: deno lint
        
      # Paso 5: Verificar la configuraci贸n de Astro
      - name: Check Astro
        run: deno run --allow-read --allow-run --allow-env --allow-net npm:astro check
        
      # Paso 6: Verificar tipos de TypeScript
      - name: Run TypeScript check
        run: deno check **/*.{ts,tsx}
        
        
      # Paso 8: Verificar el formato del c贸digo
      - name: Run Format Check
        run: deno fmt --check .