name: Lint Hacktion

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Obtener el c贸digo del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Deno en el runner
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      # Paso 3: Instalar dependencias de npm usando Deno
      - name: Install node_modules with Deno
        run: deno task npm:install
        
      # Paso 4: Ejecutar ESLint para verificar el c贸digo
      - name: Run ESLint
        run: deno task lint
        
      # Paso 5: Verificar la configuraci贸n de Astro
      - name: Check Astro
        run: deno run --allow-read --allow-run --allow-env --allow-net npm:astro check
        
      # Paso 6: Verificar tipos de TypeScript
      - name: Run TypeScript check
        run: deno check **/*.{ts,tsx}
        
      # Paso 7: Ejecutar el linter de Deno
      - name: Run Deno lint
        run: deno lint src/
        
      # Paso 8: Verificar el formato del c贸digo
      - name: Run Format Check
        run: deno fmt --check src/